# Generated by Django 4.2.1 on 2023-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
