# Generated by Django 4.2.1 on 2023-07-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_alter_cartdb_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('C_Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('C_Address', models.CharField(blank=True, max_length=50, null=True)),
                ('C_Phone', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
