# Generated by Django 4.2.1 on 2023-07-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='C_Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
